[package]
name = "rlibphonenumber-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[lib]
name = "rlibphonenumber_fuzz"
path = "src/lib.rs"


[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
cxx = "1.0"
criterion = "0.5"

[build-dependencies]
cxx-build = "1.0"

[dependencies.rlibphonenumber]
default-features = false
features = ["global_static"]
path = "../crates/rlibphonenumber"

[[bin]]
name = "full-cycle"
path = "fuzz_targets/full-cycle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff-test"
path = "fuzz_targets/diff-test.rs"
test = false
doc = false
bench = false

[features]
default = ["rlibphonenumber/lite"]

regex = ["rlibphonenumber/regex"]
