[package]
name = "rlibphonenumber-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[dependencies.rlibphonenumber]
path = "../crates/rlibphonenumber"

[[bin]]
name = "full-cycle"
path = "fuzz_targets/full-cycle.rs"
test = false
doc = false
bench = false

[[bin]]
name = "diff-test"
path = "fuzz_targets/diff-test.rs"
test = false
doc = false
bench = false
