[package]
name = "rlibphonumbers_macro"
version = "0.1.0"
edition = "2024"
description = "Package for \"Region\" enum generation for a high-performance Rust port of Google's libphonenumber for parsing, formatting, and validating international phone numbers."
repository = "https://github.com/vloldik/rlibphonenumber"

[lib]
proc-macro = true

[dependencies]
quote = "1"
xml = "1.0"
proc-macro2 = "1.0"
