name: Publish to Crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        # Multipackage publish
        uses: dtolnay/rust-toolchain@1.90.0

      - name: Run Tests
        run: cargo test

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --package rlibphonenumber --package rlibphonenumbers_macro