name: Update Metadata & Push

on:
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    update-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Generate Metadata using Dagger
              uses: dagger/dagger-for-github@v8.4.1
              with:
                  version: "latest"
                  call: generate --source . --tag latest-supported export --path .

            - name: Check for changes
              id: check
              run: |
                  if [[ -z $(git status --porcelain) ]]; then
                      echo "changes=false" >> "$GITHUB_OUTPUT"
                      echo "No changes detected by git. Skipping version bump."
                  else
                      echo "changes=true" >> "$GITHUB_OUTPUT"
                      echo "Changes detected."
                      
                      NEW_VERSION=$(grep -m1 -oP '^version\s*=\s*"\K[^"]+' crates/rlibphonenumber/Cargo.toml)
                      echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
                      echo "New version bumped to: $NEW_VERSION"
                  fi

            - name: Run Tests using Dagger
              if: steps.check.outputs.changes == 'true'
              uses: dagger/dagger-for-github@v8
              with:
                  version: "latest"
                  call: test --source . --fuzz-time 60

            - name: Create Pull Request
              if: steps.check.outputs.changes == 'true'
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "[release] Update metadata to latest and bump version to ${{ steps.check.outputs.new_version }}"
                  branch: "chore/update-metadata-${{ steps.check.outputs.new_version }}"
                  title: "Release ${{ steps.check.outputs.new_version }}. Update metadata"
                  body: |
                      Automated update of libphonenumber metadata.

                      - Metadata updated using `latest-supported` tag via Dagger pipeline.
                      - Version bumped to `${{ steps.check.outputs.new_version }}`.
                      - `dagger call test` passed successfully.
                  labels: automated-pr, release