name: Update Metadata & Push

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: 


permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          cache: maven
          java-version: '17'
          distribution: 'temurin'

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Rust
        # Required for cargo-edit
        uses: dtolnay/rust-toolchain@1.89.0

      - name: Generate Metadata
        id: generate_metadata
        run: |
          chmod +x ./tools/scripts/generate_metadata.sh
          ./tools/scripts/generate_metadata.sh --tag latest-supported --update-version
      
      - name: Run Tests
        if: steps.generate_metadata.outputs.changes == 'true'
        run: cargo test

      - name: Create Pull Request
        if: steps.generate_metadata.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[release] Update metadata to latest and bump version to ${{ steps.generate_metadata.outputs.new_version }}"
          branch: "chore/update-metadata-${{ steps.generate_metadata.outputs.new_version }}"
          title: "Release ${{ steps.generate_metadata.outputs.new_version }}. Update metadata"
          body: |
            Automated update of libphonenumber metadata.
            
            - Metadata updated using `latest-supported` tag.
            - Version bumped to `${{ steps.generate_metadata.outputs.new_version }}`.
            - `cargo test` passed.
          labels: automated-pr, release
